const translations = {
  en: {
    // Navbar
    navFeatures: "Features",
    navHowItWorks: "How it works",
    navStories: "Stories",
    navTryCoach: "Try the AI Coach",

    // Hero
    heroBadge: "Powered by FitMind's AI Coach",
    heroHeadline: "Your Personal AI Fitness Coach",
    heroSub: "Scan your meals, talk to your tracker, and get workout and nutrition plans built around you — not a generic template.",
    heroCta: "Generate my free plan",
    heroExplore: "Explore features",
    heroStat1: "~100K exercises",
    heroStat2: "8.7K+ foods recognized",
    heroStat3: "Real AI plans, not templates",

    // Features
    featuresTitle: "Everything your coach would do.",
    featuresTitleAccent: " Without the wait.",
    featMealScanner: "Meal Scanner",
    featMealScannerDesc: "Snap a photo of any meal and get an instant calorie, macro, and ingredient breakdown.",
    featVoiceTracker: "Voice Tracker",
    featVoiceTrackerDesc: "Just say what you ate or which exercises you did — it's matched and logged automatically.",
    featAiCoach: "Virtual AI Coach",
    featAiCoachDesc: "Ask questions, get adjustments, and stay accountable with a coach that's always on.",
    featPlans: "Personalized Plans",
    featPlansDesc: "Workout and nutrition plans generated from your goals, schedule, and limitations — not a template.",
    featScore: "Score & Analytics",
    featScoreDesc: "Track strength, agility, and endurance over time with a single fitness score.",
    featSafety: "Safety-Aware",
    featSafetyDesc: "Plans are checked against your injuries and conditions before they ever reach you.",

    // How it works
    howTitle: "From question one to your first workout.",
    howStep1: "Tell us about you",
    howStep1Desc: "A quick assessment — goals, body stats, experience, limitations — takes under two minutes.",
    howStep2: "AI builds your plan",
    howStep2Desc: "FitMind's coach generates a workout and nutrition plan tailored to your answers in seconds.",
    howStep3: "Track effortlessly",
    howStep3Desc: "Log meals and workouts by photo or voice. No manual search, no tedious forms.",
    howStep4: "See your score climb",
    howStep4Desc: "Strength, agility, and endurance, visualized in one score that updates as you go.",

    // Quote
    quote: "“Physical fitness can neither be acquired by wishful thinking nor by outright purchase.”",
    quoteAuthor: "— Joseph Pilates",

    // CTA
    ctaTitle: "Get your real plan in under two minutes.",
    ctaSub: "No generic templates. Answer a short assessment and FitMind's AI generates a workout and nutrition plan built around your body, goals, and limitations — for free.",
    ctaButton: "Start my assessment",

    // Footer
    footerTagline: "Built with care, coached by AI.",

    // Demo — Account
    accountTitle: "Create your free FitMind account",
    accountLoginTitle: "Welcome back",
    accountSub: "Your real plan is generated by the same AI that powers the FitMind app — we just need an account to save it to.",
    accountLoginSub: "Log in with your existing account to continue.",
    accountName: "Full name",
    accountEmail: "Email address",
    accountPassword: "Password (min 6 characters)",
    accountCreate: "Create account",
    accountLogin: "Log in",
    accountHaveAccount: "Already have an account?",
    accountNoAccount: "Don't have an account?",
    accountSignUp: "Sign up",

    // Demo — Generating
    genMessages: [
      "Reading your assessment…",
      "Checking your limitations and goals…",
      "Drafting your workout split…",
      "Balancing your macros…",
      "Running a safety pass…",
      "Double-checking exercise substitutions…",
      "Cross-referencing your injuries against the plan…",
      "Fine-tuning portion sizes…",
      "Almost there…",
    ],
    genError: "Something went wrong",
    genRetry: "Try again",
    genElapsed: "elapsed",
    genLongWait: "Plans that account for injuries or limitations go through extra AI safety checks — this can take a few minutes. Hang tight, it's still working.",

    // Demo — Profile Ready
    profileReadyTitle: "Your FitMind profile is ready!",
    profileReadySub: "We've saved your profile to your account. Want a real, AI-generated workout and nutrition plan based on it right now?",
    profileReadyCta: "Generate my plan now",
    profileReadyLater: "Maybe later",

    // Demo — Common
    commonContinue: "Continue",
    commonLoading: "Loading…",

    // Demo — Verify email
    verifyTitle: "Check your email",
    verifyEmailPrefix: "We sent a verification link to",
    verifyEmailSuffix: "Click it, then come back here to continue.",
    verifyContinue: "I've verified — continue",
    verifyResend: "Resend verification email",
    verifySending: "Sending…",

    // Demo — Plan Type Choice
    planTypeTitle: "What would you like generated?",

    // Demo — Assessment step chrome
    stepAddPlaceholder: "Add your own…",
    stepAddButton: "Add",
    stepNoneApply: "None of these apply",
    stepUnsupported: "Unsupported step.",
    ariaBack: "Back",
    ariaDecrease: "Decrease",
    ariaIncrease: "Increase",
    ariaRemove: "Remove",

    // Demo — Full plan display (results/comparison previews)
    planNutritionLabel: "Nutrition plan",
    planWorkoutLabel: "Workout plan",
    statDailyCalories: "Daily calories",
    statProtein: "Protein",
    statCarbs: "Carbs",
    statFats: "Fats",
    statFrequency: "Frequency",
    statDifficulty: "Difficulty",
    statPerSession: "Per session",
    statTrainingDays: "Training days",
    dayLabel: "Day",
    mealPrep: "Prep",
    mealCook: "Cook",
    exSets: "sets",
    exReps: "reps",
    exRest: "Rest",

    // Demo — Comparison
    compTitle: "Pick the plan you like best",
    compSub: "Three AI models generated a plan for you. Compare them and choose your favorite. This helps us find the best model for everyone.",
    compUse: "Use",
    compPlan: "plan",
    compFailed: "Generation failed:",
    compFrequency: "Frequency:",

    // Demo — Results
    resultsSaved: "Saved to your FitMind account",
    resultsTitle: "Your real plan, in full",
    resultsSub: "Take a real look before you rate it — every day, meal, and exercise below is exactly what was generated and saved to your account.",
    resultsNext: "One quick question",

    // Demo — Feedback
    fbTitle: "Rate your plan",
    fbSub: "Be honest — this directly shapes which AI model powers FitMind.",
    fbOverall: "Overall quality",
    fbClarity: "How clear and readable was the plan?",
    fbPersonalization: "How personalized did it feel to your profile?",
    fbWouldFollow: "Would you actually follow this plan?",
    fbYes: "Yes",
    fbNo: "Not really",
    fbPersonalized: "Did this feel personalized to you?",
    fbAnything: "Anything else? (optional)",
    fbPlaceholder: "What felt off, or what you loved...",
    fbSubmit: "Submit feedback",
    fbSending: "Sending...",
    fbThanks: "Thank you!",
    fbThanksSub: "Your feedback helps us pick the best AI model and make FitMind's plans more accurate for everyone.",
    fbPicked: "You picked",
    fbReveal: "We'll reveal which model won overall once we have enough votes!",
    fbHome: "Back to home",
  },

  ar: {
    // Navbar
    navFeatures: "المميزات",
    navHowItWorks: "كيف يعمل",
    navStories: "قصص",
    navTryCoach: "جرّب المدرب الذكي",

    // Hero
    heroBadge: "مدعوم بمدرب FitMind الذكي",
    heroHeadline: "مدربك الشخصي بالذكاء الاصطناعي",
    heroSub: "صوّر وجبتك، تكلّم مع المتتبع، واحصل على خطط تمارين وتغذية مصممة لك — مش قالب جاهز.",
    heroCta: "أنشئ خطتي المجانية",
    heroExplore: "اكتشف المميزات",
    heroStat1: "~100 ألف تمرين",
    heroStat2: "8.7 ألف+ وجبة معروفة",
    heroStat3: "خطط ذكية، مش قوالب",

    // Features
    featuresTitle: "كل اللي مدربك هيعمله.",
    featuresTitleAccent: " من غير انتظار.",
    featMealScanner: "ماسح الوجبات",
    featMealScannerDesc: "صوّر أي وجبة واحصل فوراً على تحليل السعرات والماكروز والمكونات.",
    featVoiceTracker: "التتبع بالصوت",
    featVoiceTrackerDesc: "قول أكلت إيه أو عملت إيه تمارين — هيتسجل تلقائياً.",
    featAiCoach: "مدرب ذكي افتراضي",
    featAiCoachDesc: "اسأل، اطلب تعديلات، وخليك ملتزم مع مدرب موجود دايماً.",
    featPlans: "خطط مخصصة",
    featPlansDesc: "خطط تمارين وتغذية مبنية على أهدافك وجدولك وظروفك الصحية — مش قالب.",
    featScore: "النتيجة والتحليلات",
    featScoreDesc: "تابع القوة والرشاقة والتحمل بنتيجة واحدة تتحدث مع تقدمك.",
    featSafety: "واعي بالسلامة",
    featSafetyDesc: "الخطط بتتراجع على إصاباتك وحالتك الصحية قبل ما توصلك.",

    // How it works
    howTitle: "من أول سؤال لأول تمرين.",
    howStep1: "قولنا عن نفسك",
    howStep1Desc: "تقييم سريع — أهدافك، جسمك، خبرتك، إصاباتك — في أقل من دقيقتين.",
    howStep2: "الذكاء الاصطناعي يبني خطتك",
    howStep2Desc: "مدرب FitMind يولّد خطة تمارين وتغذية مخصصة لإجاباتك في ثواني.",
    howStep3: "تتبّع بسهولة",
    howStep3Desc: "سجّل وجباتك وتمارينك بالصوت أو الصورة. من غير بحث يدوي أو فورم مملة.",
    howStep4: "شوف نتيجتك بتعلى",
    howStep4Desc: "القوة والرشاقة والتحمل في نتيجة واحدة بتتحدث مع كل تقدم.",

    // Quote
    quote: "“اللياقة البدنية لا تُكتسب بالتمني ولا بالشراء.”",
    quoteAuthor: "— جوزيف بيلاتيس",

    // CTA
    ctaTitle: "احصل على خطتك الحقيقية في أقل من دقيقتين.",
    ctaSub: "بدون قوالب جاهزة. جاوب تقييم قصير والذكاء الاصطناعي يولّد خطة تمارين وتغذية مبنية على جسمك وأهدافك وظروفك الصحية — مجاناً.",
    ctaButton: "ابدأ التقييم",

    // Footer
    footerTagline: "مصنوع بعناية، بتدريب الذكاء الاصطناعي.",

    // Demo — Account
    accountTitle: "أنشئ حساب FitMind مجاني",
    accountLoginTitle: "أهلاً بيك تاني",
    accountSub: "خطتك الحقيقية بيولّدها نفس الذكاء الاصطناعي اللي في تطبيق FitMind — محتاجين حساب بس عشان نحفظها.",
    accountLoginSub: "سجّل دخول بحسابك الموجود عشان تكمّل.",
    accountName: "الاسم بالكامل",
    accountEmail: "البريد الإلكتروني",
    accountPassword: "كلمة المرور (٦ حروف على الأقل)",
    accountCreate: "إنشاء حساب",
    accountLogin: "تسجيل الدخول",
    accountHaveAccount: "عندك حساب؟",
    accountNoAccount: "معندكش حساب؟",
    accountSignUp: "سجّل",

    // Demo — Generating
    genMessages: [
      "بنقرأ التقييم بتاعك…",
      "بنتحقق من إصاباتك وأهدافك…",
      "بنحضّر جدول التمارين…",
      "بنظبط الماكروز…",
      "بنعمل فحص أمان…",
      "بنراجع بدائل التمارين…",
      "بنقارن الخطة بإصاباتك…",
      "بنظبط أحجام الحصص…",
      "تقريباً خلصنا…",
    ],
    genError: "حصل مشكلة",
    genRetry: "حاول تاني",
    genElapsed: "ثانية",
    genLongWait: "الخطط اللي بتراعي الإصابات بتاخد فحوصات أمان إضافية — ممكن تاخد دقائق. استنى شوية، لسه شغال.",

    // Demo — Profile Ready
    profileReadyTitle: "بروفايلك جاهز!",
    profileReadySub: "حفظنا بروفايلك في حسابك. عايز خطة تمارين وتغذية بالذكاء الاصطناعي دلوقتي؟",
    profileReadyCta: "ولّد خطتي دلوقتي",
    profileReadyLater: "بعدين",

    // Demo — Common
    commonContinue: "التالي",
    commonLoading: "بيحمّل…",

    // Demo — Verify email
    verifyTitle: "تحقق من بريدك الإلكتروني",
    verifyEmailPrefix: "بعتنالك رابط تأكيد على",
    verifyEmailSuffix: "دوس عليه وارجع هنا تكمل.",
    verifyContinue: "أكدت — كمّل",
    verifyResend: "أعد إرسال رابط التحقق",
    verifySending: "بيتبعت…",

    // Demo — Plan Type Choice
    planTypeTitle: "عايز إيه يتولّد؟",

    // Demo — Assessment step chrome
    stepAddPlaceholder: "ضيف حاجة...",
    stepAddButton: "ضيف",
    stepNoneApply: "مفيش حاجة من دول",
    stepUnsupported: "خطوة غير مدعومة.",
    ariaBack: "رجوع",
    ariaDecrease: "قلل",
    ariaIncrease: "زود",
    ariaRemove: "شيل",

    // Demo — Full plan display (results/comparison previews)
    planNutritionLabel: "خطة تغذية",
    planWorkoutLabel: "خطة تمرين",
    statDailyCalories: "السعرات اليومية",
    statProtein: "بروتين",
    statCarbs: "كاربوهيدرات",
    statFats: "دهون",
    statFrequency: "التكرار",
    statDifficulty: "الصعوبة",
    statPerSession: "لكل حصة",
    statTrainingDays: "أيام التمرين",
    dayLabel: "يوم",
    mealPrep: "تحضير",
    mealCook: "طبخ",
    exSets: "مجموعات",
    exReps: "تكرارات",
    exRest: "راحة",

    // Demo — Comparison
    compTitle: "اختار أحسن خطة",
    compSub: "٣ نماذج ذكاء اصطناعي ولّدوا خطة ليك. قارن بينهم واختار المفضّل. ده بيساعدنا نلاقي أحسن نموذج للكل.",
    compUse: "استخدم",
    compPlan: "خطة",
    compFailed: "التوليد فشل:",
    compFrequency: "التكرار:",

    // Demo — Results
    resultsSaved: "اتحفظت في حساب FitMind بتاعك",
    resultsTitle: "خطتك الحقيقية بالكامل",
    resultsSub: "بص عليها كويس قبل ما تقيّمها — كل يوم ووجبة وتمرين تحت ده هو بالظبط اللي اتولّد واتحفظ في حسابك.",
    resultsNext: "سؤال سريع",

    // Demo — Feedback
    fbTitle: "قيّم خطتك",
    fbSub: "كن صريح — ده بيأثر مباشرة على أي نموذج ذكاء اصطناعي هيشغّل FitMind.",
    fbOverall: "الجودة العامة",
    fbClarity: "الخطة كانت واضحة وسهلة القراءة قد إيه؟",
    fbPersonalization: "حسيت إنها مخصصة لبروفايلك قد إيه؟",
    fbWouldFollow: "هتمشي على الخطة دي فعلاً؟",
    fbYes: "أيوه",
    fbNo: "مش أوي",
    fbPersonalized: "حسيت إنها مخصصة ليك؟",
    fbAnything: "حاجة تانية؟ (اختياري)",
    fbPlaceholder: "إيه اللي مش عجبك أو عجبك…",
    fbSubmit: "إرسال التقييم",
    fbSending: "بيتبعت…",
    fbThanks: "شكراً!",
    fbThanksSub: "تقييمك بيساعدنا نختار أحسن نموذج ذكاء اصطناعي ونخلّي خطط FitMind أدق للكل.",
    fbPicked: "اخترت",
    fbReveal: "هنكشف أي نموذج كسب لما يبقى عندنا أصوات كفاية!",
    fbHome: "الرجوع للرئيسية",
  },
} as const;

export type TranslationKey = keyof (typeof translations)["en"];

export function t(lang: "en" | "ar", key: TranslationKey): string | readonly string[] {
  return translations[lang][key];
}

export function ts(lang: "en" | "ar", key: TranslationKey): string {
  const val = translations[lang][key] as string | readonly string[];
  return typeof val === "string" ? val : val[0];
}

export function ta(lang: "en" | "ar", key: TranslationKey): readonly string[] {
  const val = translations[lang][key] as string | readonly string[];
  return typeof val === "string" ? [val] : val;
}
