"use client";

import { useState } from "react";
import StepShell from "./StepShell";
import ContinueButton from "./ContinueButton";

export default function AccountStep({
  stepNumber,
  totalSteps,
  onSubmit,
  loading,
  error,
}: {
  stepNumber: number;
  totalSteps: number;
  onSubmit: (name: string, email: string, password: string) => void;
  loading: boolean;
  error: string | null;
}) {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const valid = name.trim().length > 0 && /\S+@\S+\.\S+/.test(email) && password.length >= 6;

  return (
    <StepShell
      stepKey="account"
      stepNumber={stepNumber}
      totalSteps={totalSteps}
      title="Create your free FitMind account"
      footer={
        <ContinueButton
          onClick={() => onSubmit(name, email, password)}
          disabled={!valid}
          loading={loading}
          label="Create account"
        />
      }
    >
      <p className="text-sm text-muted">
        Your real plan is generated by the same AI that powers the FitMind app —
        we just need an account to save it to.
      </p>

      <div className="mt-6 flex flex-col gap-4">
        <input
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="Full name"
          className="rounded-xl border border-border bg-surface px-4 py-3.5 outline-none focus:border-brand/60"
        />
        <input
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          type="email"
          placeholder="Email address"
          className="rounded-xl border border-border bg-surface px-4 py-3.5 outline-none focus:border-brand/60"
        />
        <input
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          type="password"
          placeholder="Password (min 6 characters)"
          className="rounded-xl border border-border bg-surface px-4 py-3.5 outline-none focus:border-brand/60"
        />
      </div>

      {error && <p className="mt-4 text-sm text-red-400">{error}</p>}
    </StepShell>
  );
}
